image: node:8.11.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run test
  branches:
      develop:
        - step:
            caches:
              - node
            script: # Modify the commands below to build your repository.
              - npm install
              - npm run test
        - step:
            deployment: staging
            caches:
              - node
            script:
              - npm install
              - npm install -g now --unsafe-perm
              - npm run now:rm
              - npm run now
              - npm run now:alias