image: node:8.11.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run test
  branches:
      develop:
        - step:
            caches:
              - node
            script: # Modify the commands below to build your repository.
              - npm install
              - npm run test