# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:9.8.0

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run test
  branches:
      develop:
        - step:
            caches:
              - node
            script: # Modify the commands below to build your repository.
              - npm install
              - npm run test
        - step:
            deployment: staging
            caches:
              - node
            script:
              - npm install
              - npm install -g now --unsafe-perm
              - now rm react-next-starter --yes --token $NOW_TOKEN
              - now --token $NOW_TOKEN --npm --public -e BASE_URL="preprod.chefsquare.com"
              - now alias --token $NOW_TOKEN $NOW_URL preprod.chefsquare.com